### ISSUE TITLE
reveal-md demo OK reveal-md slides.md ERRORS

### ISSUE THREAD

**Issue by rbuchholz** [webpro/reveal-md#150]
Hi Lars,

I just updated to version 1.0.0 and I can't load my .
<img width="1209" alt="screen shot 2017-12-11 at 2 33 47 pm" src="https://user-images.githubusercontent.com/1444694/33852481-600771b6-de80-11e7-842c-0b036f9e721a.png">
md files - your demo works great...

❯ reveal-md --version
1.0.0

❯ node -v
v9.2.1

❯ npm -v
5.6.0

macOS 
10.13.1 (17B1002)

reveal-md demo - works 
❯ reveal-md slides.md
Reveal-server started at http://localhost:1948
Unhandled rejection TypeError: Cannot set property '__content' of null
    at Object.jsYaml.parse (/usr/local/lib/node_modules/reveal-md/node_modules/yaml-front-matter/lib/js-yaml-front.js:20:14)
    at Object.jsYaml.loadFront (/usr/local/lib/node_modules/reveal-md/node_modules/yaml-front-matter/lib/js-yaml-front.js:34:19)
    at parseYamlFrontMatter (/usr/local/lib/node_modules/reveal-md/lib/render.js:12:36)
    at parseSlides (/usr/local/lib/node_modules/reveal-md/lib/render.js:24:16)
    at render (/usr/local/lib/node_modules/reveal-md/lib/render.js:35:18)
    at readMarkdown.then.markdown (/usr/local/lib/node_modules/reveal-md/lib/render.js:53:33)
    at tryCatcher (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:614:10)

**Comment by webpro** [comment]
* Can you try some other Markdown file, do you still have the same issue?
* Can you please share the contents of your "slides.md" file?

**Comment by rbuchholz** [comment]
• Can you try some other Markdown file, do you still have the same issue?
- None of my Markdown files work
- I can edit your Demo files a.md and they work
- If I create a new Markdown file in your reveal-md/demo/ location it will not run
- Everything was working great

• Can you please share the contents of your "slides.md" file?
- I tried very basic files Markdown files

```
---

# Slide 01

---

```

**Comment by webpro** [comment]
Maybe the issues is in the fact that the YAML frontmatter is wrapped in dashes (`---`), but that is also the slide separator. I think not starting the file with `---` might help.

**Comment by rbuchholz** [comment]
Issue Resolved
• Do Not Start MarkDown file with --- slide separator
• Worked in previous versions < 1.0.0
Thank You!
