### ISSUE TITLE
Live reload broken

### ISSUE THREAD

**Issue by AustenLamacraft** [webpro/reveal-md#151]
Option `-w` now gives the error

```
*** DEPRECATION WARNING *** The exts option will REPLACE extensions in 0.6.4. ***
```

with no live reload

**Comment by webpro** [comment]
If anyone's interested in fixing this, please feel free to open a PR.

**Comment by medains** [comment]
livereload gives this warning if any extensions have been specified in the options

https://github.com/napcs/node-livereload/blob/e8ed7938b6e8622297b692951b3fd4c8b00946ed/lib/livereload.coffee#L30

reveal-md already uses "exts" rather than "extensions" so there's nothing to do here.

Raise an issue on livereload to remove this warning when "exts" is used properly.

**Comment by maiermic** [comment]
I get this error:

```
$ reveal-md -w src/presentation.md
*** DEPRECATION WARNING *** The exts option will REPLACE extensions in 0.6.4. ***
Reveal-server started at http://localhost:1948
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: watch /path/to/project/node_modules/parseqs/README.md ENOSPC
    at _errnoException (util.js:1003:13)
    at FSWatcher.start (fs.js:1405:19)
    at Object.fs.watch (fs.js:1431:11)
    at createFsWatchInstance (/path/to/project/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/path/to/project/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/path/to/project/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/path/to/project/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/path/to/project/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:167:5)
error Command failed with exit code 1.
```

**Comment by maiermic** [comment]
I solved my issue running:

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**Comment by webpro** [comment]
Hi @maiermic, reveal-md watches `cwd` (current working dir), so I guess there are a lot of files in there.

You may want to put the presentation (and related) files in a separate directory, and start reveal-md from there (to go without increasing open file handlers and to speed things up).

**Comment by maiermic** [comment]
Thanks for the tip :+1:

**Comment by mpas** [comment]
Placing the slides.md in a separate folder, so this folder contains only 1 file i get the same error message.

**Comment by webpro** [comment]
@mpas You also need to start reveal-md from inside that folder.

Closing this one. If anyone still has issues, please open a new ticket.
