### ISSUE TITLE
Images from web in static site

### ISSUE THREAD

**Issue by antifermion** [webpro/reveal-md#182]
If images are embedded as http URI, the following error is printed when attempting to render as a static site:

```
ImageDataURI :: Error :: {
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/home/dorian/projects/ctf/34c3ctf/hardotp/pres/https:/upload.wikimedia.org/wikipedia/commons/e/e4/LFSR-Fibonacci.svg"
}
TypeError: Cannot read property 'replace' of undefined
    at parseYamlFrontMatter (/usr/lib/node_modules/reveal-md/lib/render.js:12:54)
    at parseSlides (/usr/lib/node_modules/reveal-md/lib/render.js:24:16)
    at render (/usr/lib/node_modules/reveal-md/lib/render.js:35:18)
    at parseSlideAwait.then.then.markdown (/usr/lib/node_modules/reveal-md/lib/static.js:55:23)
    at tryCatcher (/usr/lib/node_modules/reveal-md/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/reveal-md/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/reveal-md/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/reveal-md/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

**Comment by webpro** [comment]
Can you guys please try again with version 2.0.0-rc.4? Feel free to (re)open tickets if any issues occur.

```
npm install reveal-md@rc --global
```
