### ISSUE TITLE
export as Static Website fails

### ISSUE THREAD

**Issue by kaischleicher** [webpro/reveal-md#208]
fist, thanks for this awesome tool!
I wish to export my presentation as static website, but ran into issues (with puppeteer?).
I have node v10.9.0, npm v6.2.0, reveal-md v2.1.0 and am using linux mint 18.3.

- a fresh installation of reveal-md using `npm install -g reveal-md` finished with an error "Failed to download Chromium r549031!", even when using root rights.
- I managed an error-free installation, which required root rights and `npm install -g reveal-md --unsafe-perm=true --allow-root`
- However, exporting as static using `reveal-md demo.md --static` still fails with an error "Error: Failed to launch chrome!"
This results in a static websites that lacks all images. See below for the full output with the error message.

```
[0903/121506.286273:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.
[0903/121506.286372:FATAL:content_main_delegate.cc(53)] Check failed: false. 
#0 0x56139a4d7b0c base::debug::StackTrace::StackTrace()
#1 0x56139a4f0780 logging::LogMessage::~LogMessage()
#2 0x561398879d23 content::ContentMainDelegate::TerminateForFatalInitializationError()
#3 0x56139a212deb content::ContentMainRunnerImpl::Initialize()
#4 0x56139a21cb72 service_manager::Main()
#5 0x56139a211f14 content::ContentMain()
#6 0x56139e3219b9 headless::(anonymous namespace)::RunContentMain()
#7 0x56139e321a42 headless::HeadlessBrowserMain()
#8 0x56139a219f9d headless::HeadlessShellMain()
#9 0x5613988781ac ChromeMain
#10 0x7fbe01e77830 __libc_start_main
#11 0x56139887802a _start



TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Error: Failed to launch chrome!
[0903/121506.286273:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.
[0903/121506.286372:FATAL:content_main_delegate.cc(53)] Check failed: false. 
#0 0x56139a4d7b0c base::debug::StackTrace::StackTrace()
#1 0x56139a4f0780 logging::LogMessage::~LogMessage()
#2 0x561398879d23 content::ContentMainDelegate::TerminateForFatalInitializationError()
#3 0x56139a212deb content::ContentMainRunnerImpl::Initialize()
#4 0x56139a21cb72 service_manager::Main()
#5 0x56139a211f14 content::ContentMain()
#6 0x56139e3219b9 headless::(anonymous namespace)::RunContentMain()
#7 0x56139e321a42 headless::HeadlessBrowserMain()
#8 0x56139a219f9d headless::HeadlessShellMain()
#9 0x5613988781ac ChromeMain
#10 0x7fbe01e77830 __libc_start_main
#11 0x56139887802a _start



TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/lib/Launcher.js:255:14)
    at Interface.helper.addEventListener (/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/lib/Launcher.js:244:50)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by webpro** [comment]
Hi @kaischleicher, thanks! Are you able to install puppeteer itself? I.e. `npm install -g puppeteer`. Maybe there's an issue with installing npm packages (or puppeteer specifically) globally.

**Comment by kaischleicher** [comment]
Hi @webpro, `npm install -g puppeteer` unfortunately also fails with the same error (even when using root rightsr) as the first point mentioned, i.e. 

> "Failed to download Chromium r549031!"

See below for the full output with the error message:
```
> puppeteer@1.7.0 install /usr/local/lib/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r579032! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.7.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-04T07_30_20_495Z-debug.log

```

**Comment by webpro** [comment]
That tells me the issue most likely isn't in reveal-md. All the information is in the log you posted. If you still have problems with reveal-md if this has been solved, feel free to re-open!
