### ISSUE TITLE
How to kill/terminate the background reveal-md server

### ISSUE THREAD

**Issue by yakir12** [webpro/reveal-md#238]
I started a session with `&` at the end (as part of a series of shell commands I want to run from a `.sh` file):
```shell
reveal-md main.md &
```
and if I try running the same file again I get the following. I interpret it as that that specific gate is already used by the previous session. Any easy way to kill the previous session? I can't find anything obvious (to me) in `htop`...
```shell
Reveal-server started at http://localhost:1948
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1948
    at Server.setupListenHandle [as _listen2] (net.js:1256:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1392:7)
    at Function.listen (/usr/lib/node_modules/reveal-md/node_modules/express/lib/application.js:618:24)
    at startServer (/usr/lib/node_modules/reveal-md/lib/serve.js:47:22)
    at revealMarkdown (/usr/lib/node_modules/reveal-md/lib/index.js:21:5)
    at Object.<anonymous> (/usr/lib/node_modules/reveal-md/bin/cli.js:60:1)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
Emitted 'error' event at:
    at emitErrorNT (net.js:1283:8)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
```
Thanks!!!

**Comment by webpro** [comment]
Hi @yakir12! Not a reveal-md issue, but you can do e.g.

```
ps aux | grep reveal-md
```

to find the `pid` and kill the process.

**Comment by yakir12** [comment]
Ah! Perfect, Thanks a lot!!!
