### ISSUE TITLE
Unable to print

### ISSUE THREAD

**Issue by marcbria** [webpro/reveal-md#253]
When I ask for a printed version as follows:
`$reveal-md about.md --print about.pdf`

I get the following error:
```
Reveal-server started at localhost:1948
Attempting to print "about.md" to "about.pdf".
Error while generating PDF for "about.md"
```

I don't see a verbose option or a log to report it better.

**Comment by webpro** [comment]
You can try this:

```
DEBUG=reveal-md reveal-md about.md --print about.pdf
```

**Comment by marcbria** [comment]
Thanks. This is the output:

```
$ DEBUG=reveal-md reveal-md about.md --print about.pdf > about.log
  reveal-md { initialUrl: 'http://localhost:1948/about.md',
  reveal-md   printPluginPath: '/usr/local/lib/node_modules/reveal-md/node_modules/reveal.js/plugin/print-pdf/print-pdf.js',
  reveal-md   pdfFilename: 'about.pdf',
  reveal-md   puppeteerLaunchConfig: { args: null, executablePath: null } } +0ms
Error while generating PDF for "about.md"
  reveal-md Error: Failed to launch chrome!
  reveal-md [0605/154013.297979:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.
  reveal-md [0605/154013.298132:FATAL:content_main_delegate.cc(53)] Check failed: false. 
  reveal-md #0 0x561545fa2b0c base::debug::StackTrace::StackTrace()
  reveal-md #1 0x561545fbb780 logging::LogMessage::~LogMessage()
  reveal-md #2 0x561544344d23 content::ContentMainDelegate::TerminateForFatalInitializationError()
  reveal-md #3 0x561545cdddeb content::ContentMainRunnerImpl::Initialize()
  reveal-md #4 0x561545ce7b72 service_manager::Main()
  reveal-md #5 0x561545cdcf14 content::ContentMain()
  reveal-md #6 0x561549dec9b9 headless::(anonymous namespace)::RunContentMain()
  reveal-md #7 0x561549deca42 headless::HeadlessBrowserMain()
  reveal-md #8 0x561545ce4f9d headless::HeadlessShellMain()
  reveal-md #9 0x5615443431ac ChromeMain
  reveal-md #10 0x7f7b35dafb97 __libc_start_main
  reveal-md #11 0x56154434302a _start
  reveal-md 
  reveal-md 
  reveal-md 
  reveal-md TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
  reveal-md 
  reveal-md     at onClose (/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/lib/Launcher.js:255:14)
  reveal-md     at Interface.helper.addEventListener (/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/lib/Launcher.js:244:50)
  reveal-md     at emitNone (events.js:111:20)
  reveal-md     at Interface.emit (events.js:208:7)
  reveal-md     at Interface.close (readline.js:370:8)
  reveal-md     at Socket.onend (readline.js:149:10)
  reveal-md     at emitNone (events.js:111:20)
  reveal-md     at Socket.emit (events.js:208:7)
  reveal-md     at endReadableNT (_stream_readable.js:1064:12)
  reveal-md     at _combinedTickCallback (internal/process/next_tick.js:138:11) +349ms

```

**Comment by webpro** [comment]
> Error: Failed to launch chrome!

What OS are you on? Was Puppeteer successfully installed? It's probably a problem with Puppeteer.

**Comment by marcbria** [comment]
> What OS are you on? 
Ubuntu 18.04.1 LTS

> Was Puppeteer successfully installed? 
Wasn't but I installed it now and the error it's the same.

> It's probably a problem with Puppeteer.
Probably you are right. I will dig in this line.

Thanks for your help,
m.

**Comment by opsdisk** [comment]
@marcbria This worked for me:

```bash
DEBUG=reveal-md reveal-md presentation.md --print presentation.pdf --puppeteer-chromium-executable="/opt/google/chrome/chrome"
```

**Comment by marcbria** [comment]
Thanks a lot @opsdisk for the tip.
It works, but mess my presentation:
1) adding a white frame around the slide. 
2) with a page size to little.

I think I remember a reveal-md parameter for the pagesize, but I'm unsure about the white frame.

**Comment by opsdisk** [comment]
Yeah, I get the same white frame as well.  It created some blank pages because the margins were exceeded for fuller pages.  I'm not really familiar with using puppeteer.

**Comment by frankgerhardt** [comment]
I have the same error. Puppeteer was installed fine, with minor warnings.

```
$ npm install -g reveal-md
/home/user/.nvm/versions/node/v11.10.0/bin/reveal-md -> /home/user/.nvm/versions/node/v11.10.0/lib/node_modules/reveal-md/bin/reveal-md.js

> puppeteer@1.3.0 install /home/user/.nvm/versions/node/v11.10.0/lib/node_modules/reveal-md/node_modules/puppeteer
> node install.js

Downloading Chromium r549031 - 97 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/user/.nvm/versions/node/v11.10.0/lib/node_modules/reveal-md/node_modules/puppeteer/.local-chromium/linux-549031
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/reveal-md/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ reveal-md@3.0.4
added 389 packages from 459 contributors in 25.659s
```

I don't have Chrome installed but used `--puppeteer-chromium-executable="/usr/bin/chromium"`. 

It worked but the process never terminates. Still serving the web page? Not expected. Rather that it terminates when the pdf is ready.

**Comment by frankgerhardt** [comment]
I also have the white margin and some slides are 2 pages in pdf because content flows over from the first page to the second. It would be nice if the content would be on one page and displayed as in the HTML.

**Comment by webpro** [comment]
The original issue seems to be resolved (by setting the `--puppeteer-chromium-executable` param). I have updated the docs with this.

Please open a PR or open new a new issue for the PDF layout issues. I can already say I that personally I'm not too interested in fixing these myself.
