### ISSUE TITLE
Node.js error on Docker container

### ISSUE THREAD

**Issue by gabrielesh** [webpro/reveal-md#277]
Hi, and thank you for a great project! When I tried to run slides using the Docker container you suggest, I got the following error message: 
Reveal-server started at localhost:1948
(node:1) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, scandir '/proc/1/map_files/2645000-2647000'
    at Object.readdirSync (fs.js:790:3)
    at GlobSync._readdir (/app/node_modules/glob/sync.js:288:41)
    at GlobSync._readdirInGlobStar (/app/node_modules/glob/sync.js:267:20)
    at GlobSync._readdir (/app/node_modules/glob/sync.js:276:17)
    at GlobSync._processReaddir (/app/node_modules/glob/sync.js:137:22)
    at GlobSync._process (/app/node_modules/glob/sync.js:132:10)
    at GlobSync._processGlobStar (/app/node_modules/glob/sync.js:380:10)
    at GlobSync._process (/app/node_modules/glob/sync.js:130:10)
    at GlobSync._processGlobStar (/app/node_modules/glob/sync.js:383:10)
    at GlobSync._process (/app/node_modules/glob/sync.js:130:10)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My docker command was as follows, in case that is where the error lies: 2017-01-09-dundee ghayden$ docker run --rm -p 1948:1948 -v "/Users/[redacted for privacy]/Outreach and Teaching/Workshops/Git/Teaching-SWC-Lessons-master/git/2017-01-09-dundee/slides_git.md":/slides webpronl/reveal-md:latest

Docker shows the container up and running, with the image webpronl/reveal-md:latest. Docker Engine -- Community has just been updated to 19.03.4. Running on Mac 10.14.6.

I suspect this is may be user error, and apologize if I'm missing something obvious.

Thank you

**Comment by gabrielesh** [comment]
Figured out my error. Thanks! Working smoothly.
