### ISSUE TITLE
Use print in a CI environment

### ISSUE THREAD

**Issue by TribuneX** [webpro/reveal-md#299]
Hi,

I am trying to get the following command working in a Gitlab CI pipeline:

```
pdf:
  stage: pdf
  image: buildkite/puppeteer
  script: 
    - npm install -g reveal-md
    - reveal-md slides/slides.md --print pdf/
  artifacts:
    paths:
    - pdf/
```

Unfortunately, I can't get puppeteer to get installed. Therefore, I tried to use an image which has puppeteer already installed. Any hints on how to get puppeteer working with reveal-md in a CI environment?

```
Downloading artifacts from coordinator... ok        id=398994076 responseStatus=200 OK token=WcGqvhWh
18
$ npm install -g reveal-md
19 /usr/local/bin/reveal-md -> /usr/local/lib/node_modules/reveal-md/bin/reveal-md.js
20 > puppeteer@1.19.0 install /usr/local/lib/node_modules/reveal-md/node_modules/puppeteer
21 > node install.js
22 ERROR: Failed to download Chromium r674921! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
23 { Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/.local-chromium'
24   -- ASYNC --
25     at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/lib/helper.js:111:15)
26     at Object.<anonymous> (/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/install.js:64:16)
27     at Module._compile (internal/modules/cjs/loader.js:701:30)
28     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
29     at Module.load (internal/modules/cjs/loader.js:600:32)
30     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
31     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
32     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
33     at startup (internal/bootstrap/node.js:283:19)
34     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
35   errno: -13,
36   code: 'EACCES',
37   syscall: 'mkdir',
38   path:
39    '/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/.local-chromium' }
40 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/reveal-md/node_modules/fsevents):
41 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
42 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@1.19.0 (node_modules/reveal-md/node_modules/puppeteer):
43 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@1.19.0 install: `node install.js`
44 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
45 + reveal-md@3.4.2
```

**Comment by webpro** [comment]
You can use the `--puppeteer-chromium-executable` argument (see https://github.com/webpro/reveal-md#print-to-pdf and/or `reveal-md --help`).

**Comment by TribuneX** [comment]
Thanks I am still truckling though to install puppeteer properly in a docker container. Ideally it would be already included in the reveal-md image.

**Comment by TribuneX** [comment]
I just investigated the reveal-md docker image further. It seems that puppeteer and the local chromium is installed during the docker build process. However, if I try to print my slides with the container image i get the following error:

```
Error while generating PDF for "slides.md"
reveal    | 2020-01-12T21:25:29.074Z reveal-md Error: Failed to launch chrome!
reveal    | /app/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```

While building the image manually from the Dockerfile in this repo, I can see that puppeteer gets installed:

```
 ---> Running in 061a8bbd4572

> puppeteer@1.19.0 install /app/node_modules/puppeteer
> node install.js


Chromium downloaded to /app/node_modules/puppeteer/.local-chromium/linux-674921
```

**Comment by TribuneX** [comment]
I got it working. Puppeteer with docker requires some additional dependencies:
https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

I'll work on a PR for this.

**Comment by webpro** [comment]
Thanks, @TribuneX! Looking forward to your PR.

**Comment by TribuneX** [comment]
I‘ll submit a PR once it is ready. This issue can be closed.
