### ISSUE TITLE
Local test failures

### ISSUE THREAD

**Issue by NukeManDan** [webpro/reveal-md#452]
Locally running `yarn install; yarn test` yields:

```sh
✖ should render custom css, after theme
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(actual.includes(style1Link))

    at /home/nuke/git/reveal-md/test/render.spec.js:43:3 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
✖ should render custom scripts
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(actual.includes('<script src="./_assets/custom.js"></script>'))

    at /home/nuke/git/reveal-md/test/render.spec.js:31:3 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by webpro** [comment]
Can't reproduce this, so not sure what I should do. Tests run fine here.
