### ISSUE TITLE
Bug with 0.0.29 and --static

### ISSUE THREAD

**Issue by november-eleven** [webpro/reveal-md#69]
Hello,

There is a bug with the latest release of reveal-md when you use the `--static` option.

For example, with this command:

```bash
reveal-md slides.md --static \
		--theme style --highlightTheme monokai-sublime > index.html
```

It produces this stack:

```
/usr/lib/node_modules/reveal-md/bin/server.js:55
    options.scripts.forEach(function(script) {
                   ^

TypeError: Cannot read property 'forEach' of undefined
    at fillOpts (/usr/lib/node_modules/reveal-md/bin/server.js:55:20)
    at Object.to_html [as toStaticHTML] (/usr/lib/node_modules/reveal-md/bin/server.js:191:5)
    at Object.<anonymous> (/usr/lib/node_modules/reveal-md/bin/cli.js:111:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
```

I've "fixed" this issue by hacking fillOpts using this code:

```js
var fillOpts = function(options) {
    [...]
    opts.scripts = {};
    if(options.scripts) {
        options.scripts.forEach(function(script) {
             opts.scripts[path.basename(script)] = script;
        });
    }
};
```

Since I'm not an expert in JS, I let you fix this issue as you prefer.

Thank you in advance.

**Comment by webpro** [comment]
Should be fixed by #70 now in [0.0.30](https://github.com/webpro/reveal-md/releases/tag/0.0.30).
