### ISSUE TITLE
TypeError when using reveal.js-menu script

### ISSUE THREAD

**Issue by jat255** [webpro/reveal-md#80]
Hi there,

When calling `reveal-md` with the following:

```bash
reveal-md presentation.md --scripts reveal.js-menu/menu.js
```

I get the following error:
```python
Reveal-server started, opening at http://localhost:1948
TypeError: path argument is required to res.sendFile
    at ServerResponse.sendFile (C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\node_modules\express\lib\response.js:393:11)
    at getScript (C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\bin\server.js:161:9)
    at Layer.handle [as handle_request] (C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\node_modules\express\lib\router\index.js:277:22
    at param (C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\node_modules\express\lib\router\index.js:349:14)
    at param (C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\jat\AppData\Roaming\npm\node_modules\reveal-md\node_modules\express\lib\router\index.js:410:3)
```

And the menu plugin does not work as expected.

Here is my setup:
```
reveal-md --version
0.0.31
```
```
node --version
v6.9.1
```

**Comment by webpro** [comment]
The location of `reveal.js-menu/menu.js` is resolved from the path where the command is issued (not from the `node_modules` folder). Does that help?

**Comment by jat255** [comment]
Unfortunately, no. I have the script file in the right place and the command is finding the script perfectly fine, but it's complaining on that call to `res.sendFile`.

**Comment by webpro** [comment]
If I put a simple `console.log(1)` in that script, it _works in my machine™_. Please provide more information, otherwise there's not much I can do.

**Comment by jat255** [comment]
I can't figure out why it's not working either. I just forked the repo and added the plugin to the  `template.html` file, which worked for me.
