### ISSUE TITLE
0.1.2 speaker notes are not working

### ISSUE THREAD

**Issue by MansM** [webpro/reveal-md#93]
Got total blank screens, did work in 0.1.1

**Comment by IronhandedLayman** [comment]
I can verify this bug. In addition, I get the following error on the console when going into speaker mode:
```
Unhandled rejection TypeError: path must be a string or Buffer
    at TypeError (native)
    at fs.readFile (fs.js:303:11)
    at go$readFile (/opt/local/lib/node_modules/reveal-md/node_modules/graceful-fs/graceful-fs.js:73:14)
    at Object.readFile (/opt/local/lib/node_modules/reveal-md/node_modules/graceful-fs/graceful-fs.js:70:12)
    at Object.tryCatcher (/opt/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/util.js:16:23)
    at Object.ret [as readFileAsync] (eval at makeNodePromisifiedEval (/opt/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at renderMarkdownAsSlides (/opt/local/lib/node_modules/reveal-md/lib/render.js:59:10)
    at Layer.handle [as handle_request] (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/route.js:131:13)
    at updatePathOptions (/opt/local/lib/node_modules/reveal-md/lib/serve.js:19:3)
    at Layer.handle [as handle_request] (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/layer.js:95:5)
    at /opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/index.js:277:22
    at param (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/index.js:349:14)
Unhandled rejection TypeError: path must be a string or Buffer
    at TypeError (native)
    at fs.readFile (fs.js:303:11)
    at go$readFile (/opt/local/lib/node_modules/reveal-md/node_modules/graceful-fs/graceful-fs.js:73:14)
    at Object.readFile (/opt/local/lib/node_modules/reveal-md/node_modules/graceful-fs/graceful-fs.js:70:12)
    at Object.tryCatcher (/opt/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/util.js:16:23)
    at Object.ret [as readFileAsync] (eval at makeNodePromisifiedEval (/opt/local/lib/node_modules/reveal-md/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at renderMarkdownAsSlides (/opt/local/lib/node_modules/reveal-md/lib/render.js:59:10)
    at Layer.handle [as handle_request] (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/route.js:131:13)
    at updatePathOptions (/opt/local/lib/node_modules/reveal-md/lib/serve.js:19:3)
    at Layer.handle [as handle_request] (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/layer.js:95:5)
    at /opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/index.js:277:22
    at param (/opt/local/lib/node_modules/reveal-md/node_modules/express/lib/router/index.js:349:14)
```

**Comment by webpro** [comment]
What works for me: `reveal-md ./demo/a.md ` and then press `S` on the first slide. Also, I'm not seeing errors.

If you can post markdown and/or reproducible steps, I can take a look.

**Comment by webpro** [comment]
Closing due to inactivity.

**Comment by runeflobakk** [comment]
I too experience this, and I think I have figured out when it happens. If I start the server with `reveal-md slides.md` the speaker notes shows just fine, but if I just run `reveal-md`, without providing the name of my markdown file, I get the same exception as @IronhandedLayman.
